// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const creationMoments = [
  {
    id: 'start',
    name: 'Start locally',
    owner: 'You · workstation',
    title: 'Prepare access before creating resources.',
    copy: 'Install the CLI and tools, sign in, and confirm the target subscription. spi check validates tools; it does not check login, subscription selection, or role-assignment permissions.',
    commands: ['spi --version', 'az login', 'az account show', 'spi check'],
    commandLabel: 'After installing the tools',
    action: 'Prepare access',
    detail: 'workstation',
    state: 'Planned environment',
    time: 'Before provisioning',
  },
  {
    id: 'provision',
    name: 'Create Azure',
    owner: 'SPI CLI + Bicep',
    title: 'AKS comes first. Azure backends follow.',
    copy: 'One spi up invocation creates the cluster, obtains its OIDC issuer, then provisions the data services and identities that depend on it.',
    commands: ['spi up --env <name>'],
    commandLabel: 'Run once to create the environment',
    action: 'Provision resources',
    detail: 'aks',
    state: 'Azure resources created',
    time: 'AKS ≈30 min',
    timeKind: 'Observed component time',
  },
  {
    id: 'bootstrap',
    name: 'Prepare AKS',
    owner: 'SPI CLI · bootstrap',
    title: 'Prepare cluster configuration and identity.',
    copy: 'The same invocation supplies namespaces, configuration, seed credentials, and identity bindings. Workloads will consume these inputs when Flux starts.',
    commands: ['spi up --env <name>'],
    commandLabel: 'Still the same invocation',
    action: 'Seed cluster inputs',
    detail: 'bootstrap',
    state: 'Cluster prepared',
    time: 'Within ≈45–50 min provisioning',
    timeKind: 'Observed total, not a separate timer',
  },
  {
    id: 'reconcile',
    name: 'Assemble OSDU',
    owner: 'Flux · inside AKS',
    title: 'Dependencies become workloads, then initialized APIs.',
    copy: 'Flux assembles operators, middleware, OSDU services, and initialization jobs. This overlaps the final CLI work; a successful exit can precede API readiness.',
    commands: ['spi up --env <name>'],
    commandLabel: 'Flux starts before the CLI finishes',
    action: 'Activate reconciliation',
    detail: 'initialization',
    state: 'Rollout in progress',
    time: 'Flux setup ≈10–15 min',
    timeKind: 'Observed component time; overlaps',
  },
  {
    id: 'inspect',
    name: 'Use the stack',
    owner: 'You · observe and call',
    title: 'Follow readiness, then make an OSDU call.',
    copy: 'Check health and initialization, discover an API endpoint, and get a token for an authenticated readiness check.',
    commands: [
      'spi status --watch',
      'spi info --show-apis',
      'TOKEN=$(spi token)',
    ],
    commandLabel: 'On the connected environment',
    action: 'Inspect and use',
    detail: 'readiness',
    state: 'Assembled example',
    time: 'Readiness varies',
    timeKind: '150 min is the schema Job deadline',
  },
  {
    id: 'remove',
    name: 'Remove the stack',
    owner: 'You · teardown',
    title: 'Remove compute and data. Keep the identity footprint.',
    copy: 'When your environment is no longer needed, ordinary spi down deletes the cluster and application data. Managed identities, the resource group, and naming tags remain.',
    commands: ['spi down --env <name>'],
    commandLabel: 'Deletes this environment’s compute and data',
    action: 'Remove the environment',
    detail: 'retained',
    state: 'Retained footprint',
    time: '45 min deletion deadline',
    timeKind: 'Timeout, not a promised duration',
  },
];
