// A day in a service fork, as moments on the branch map. Times are the
// scheduled triggers in the template workflows; nothing here is measured.
export const forkMoments = [
  {
    id: 'sync',
    name: 'Generate',
    owner: 'Sync Upstream · 00:00 UTC',
    title: 'The upstream branch is printed again, not merged.',
    copy: 'The filter reads the upstream tip, keeps the shared modules, drops the other providers, injects the Azure profile, and writes the result as a new commit on fork_upstream with two parents. One PR and one tracking issue carry it.',
    action: 'Regenerate fork_upstream from the upstream tip',
    detail: 'sync-pr',
    time: 'Daily, 00:00 UTC',
    timeKind: 'Scheduled trigger',
    active: ['upstream', 'fork-upstream'],
  },
  {
    id: 'cascade',
    name: 'Integrate',
    owner: 'Cascade Integration',
    title: 'The fix and the upstream change meet in the workspace.',
    copy: 'The cascade resets fork_integration to main, merges fork_upstream into it, and builds with -P core,azure. This is the first time the fork-owned provider compiles against the new shared code.',
    action: 'Merge main, then fork_upstream, into fork_integration',
    detail: 'cascade-run',
    time: 'After the sync PR merges',
    timeKind: 'Event, or the monitor within 6 hours',
    active: ['fork-upstream', 'fork-integration', 'main-branch'],
  },
  {
    id: 'review',
    name: 'Wait',
    owner: 'A person · labels',
    title: 'Nothing moves to main without a person, and the labels say why.',
    copy: 'A clean cascade opens a release/upstream-* PR labeled validated. A conflict or a failed build leaves cascade-blocked or cascade-failed with human-required on the tracking issue. Removing human-required is the retry signal.',
    action: 'Review the release PR, or resolve the conflict',
    detail: 'labels',
    time: 'Until a person acts',
    timeKind: 'Escalated after 48 hours blocked',
    active: ['fork-integration', 'main-branch'],
  },
  {
    id: 'release',
    name: 'Release',
    owner: 'Release Please',
    title: 'The image is retagged, not rebuilt.',
    copy: 'After the release PR merges, Release Please tags main and a correlation tag records the upstream version. The workflow waits for the sha-* image that validation already pushed and adds the version tag to it.',
    action: 'Tag main and the image that already exists',
    detail: 'release-tag',
    time: 'After the release PR merges',
    timeKind: 'Polls the registry, 60 × 20 s',
    active: ['main-branch', 'image'],
  },
  {
    id: 'template',
    name: 'Receive',
    owner: 'Sync Template · 08:00 UTC',
    title: 'The engineering system arrives the same way upstream does.',
    copy: 'Changes to the workflows in osdu-spi reach every service fork as a PR labeled template-sync, at most one open at a time. Mondays at 04:00 UTC, Settings Apply reconciles labels, rulesets, and required checks.',
    action: 'Open or update the template-sync PR',
    detail: 'template-pr',
    time: 'Daily, 08:00 UTC',
    timeKind: 'Scheduled trigger',
    active: ['engineering', 'main-branch'],
  },
];
