export const sources = {
  architecture: {
    label: 'Stack architecture (dc2c956)',
    repo: 'osdu-spi-stack',
    path: 'docs/architecture.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/dc2c95638ded6459538085cfdb2ada46b692c27b/docs/architecture.md',
    revision: 'dc2c95638ded6459538085cfdb2ada46b692c27b',
  },
  lifecycle: {
    label: 'Deployment and teardown',
    repo: 'osdu-spi-stack',
    path: 'docs/design/deployment-lifecycle.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/deployment-lifecycle.md',
  },
  identity: {
    label: 'Workload Identity and API callers',
    repo: 'osdu-spi-stack',
    path: 'docs/design/workload-identity.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/workload-identity.md',
  },
  flux: {
    label: 'Flux dependency ordering',
    repo: 'osdu-spi-stack',
    path: 'docs/design/flux-reconciliation.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/flux-reconciliation.md',
  },
  install: {
    label: 'Install the SPI CLI',
    repo: 'osdu-spi-stack',
    path: 'docs/install.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/install.md',
  },
  images: {
    label: 'Image sources and canonical policy',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/033-explicit-canonical-image-source-policy.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/033-explicit-canonical-image-source-policy.md',
  },
  forkDeploy: {
    label: 'Fork deployment contract',
    repo: 'osdu-spi-stack',
    path: 'docs/design/fork-deployment.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/fork-deployment.md',
  },
  partitionRepo: {
    label: 'osdu-spi-partition on GitHub',
    repo: 'osdu-spi-partition',
    path: 'README.md',
    href: 'https://github.com/Azure/osdu-spi-partition',
  },
  partitionPom: {
    label: 'Partition Azure provider POM (3a5690d)',
    repo: 'osdu-spi-partition',
    path: 'provider/partition-azure/pom.xml',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/3a5690da3147d022ca9a2402858cd7b96e4688cf/provider/partition-azure/pom.xml',
    revision: '3a5690da3147d022ca9a2402858cd7b96e4688cf',
  },
  partitionDockerfile: {
    label: 'Partition service Dockerfile',
    repo: 'osdu-spi-partition',
    path: 'build/Dockerfile',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/main/build/Dockerfile',
  },
  partitionEntrypoint: {
    label: 'Partition service entry point',
    repo: 'osdu-spi-partition',
    path: 'build/docker-entrypoint.sh',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/main/build/docker-entrypoint.sh',
  },
  partitionProvider: {
    label: 'PartitionServiceImpl, the Azure provider (3a5690d)',
    repo: 'osdu-spi-partition',
    path: 'provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/service/PartitionServiceImpl.java',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/3a5690da3147d022ca9a2402858cd7b96e4688cf/provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/service/PartitionServiceImpl.java',
    revision: '3a5690da3147d022ca9a2402858cd7b96e4688cf',
  },
  partitionRedis: {
    label: 'Azure Partition Redis configuration (3a5690d)',
    repo: 'osdu-spi-partition',
    path: 'provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/di/RedisConfig.java',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/3a5690da3147d022ca9a2402858cd7b96e4688cf/provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/di/RedisConfig.java',
    revision: '3a5690da3147d022ca9a2402858cd7b96e4688cf',
  },
  partitionTableStore: {
    label: 'Azure Partition Table Storage client (3a5690d)',
    repo: 'osdu-spi-partition',
    path: 'provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/persistence/DataTableStore.java',
    href: 'https://github.com/Azure/osdu-spi-partition/blob/3a5690da3147d022ca9a2402858cd7b96e4688cf/provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/persistence/DataTableStore.java',
    revision: '3a5690da3147d022ca9a2402858cd7b96e4688cf',
  },
  communityPartitionInterface: {
    label: 'Community Partition provider interface (5aa406b9)',
    repo: 'partition',
    path: 'partition-core/src/main/java/org/opengroup/osdu/partition/provider/interfaces/IPartitionService.java',
    href: 'https://community.opengroup.org/osdu/platform/system/partition/-/blob/5aa406b978dec178fe05f1c9a0ee0ca02eb239b4/partition-core/src/main/java/org/opengroup/osdu/partition/provider/interfaces/IPartitionService.java',
    revision: '5aa406b978dec178fe05f1c9a0ee0ca02eb239b4',
  },
  communityPartitionProvider: {
    label: 'Community PartitionServiceImpl (5aa406b9)',
    repo: 'partition',
    path: 'partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/service/PartitionServiceImpl.java',
    href: 'https://community.opengroup.org/osdu/platform/system/partition/-/blob/5aa406b978dec178fe05f1c9a0ee0ca02eb239b4/partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/service/PartitionServiceImpl.java',
    revision: '5aa406b978dec178fe05f1c9a0ee0ca02eb239b4',
  },
  communityPartitionCache: {
    label: 'Community Partition VmCache configuration (5aa406b9)',
    repo: 'partition',
    path: 'partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/cache/VmCacheConfiguration.java',
    href: 'https://community.opengroup.org/osdu/platform/system/partition/-/blob/5aa406b978dec178fe05f1c9a0ee0ca02eb239b4/partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/cache/VmCacheConfiguration.java',
    revision: '5aa406b978dec178fe05f1c9a0ee0ca02eb239b4',
  },
  communityPartitionRepository: {
    label: 'Community Partition OSM repository (5aa406b9)',
    repo: 'partition',
    path: 'partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/osm/repository/OsmPartitionPropertyRepository.java',
    href: 'https://community.opengroup.org/osdu/platform/system/partition/-/blob/5aa406b978dec178fe05f1c9a0ee0ca02eb239b4/partition-core-plus/src/main/java/org/opengroup/osdu/partition/coreplus/osm/repository/OsmPartitionPropertyRepository.java',
    revision: '5aa406b978dec178fe05f1c9a0ee0ca02eb239b4',
  },
  communityPartitionPom: {
    label: 'Community Partition core-plus POM (5aa406b9)',
    repo: 'partition',
    path: 'partition-core-plus/pom.xml',
    href: 'https://community.opengroup.org/osdu/platform/system/partition/-/blob/5aa406b978dec178fe05f1c9a0ee0ca02eb239b4/partition-core-plus/pom.xml',
    revision: '5aa406b978dec178fe05f1c9a0ee0ca02eb239b4',
  },
  cimplArchitecture: {
    label: 'CIMPL Stack architecture (fe56aa1b)',
    repo: 'cimpl-stack',
    path: 'docs/architecture.md',
    href: 'https://community.opengroup.org/osdu/platform/deployment-and-operations/cimpl-stack/-/blob/fe56aa1b13e9a15aee8af97f103484f8240a9cb3/docs/architecture.md',
    revision: 'fe56aa1b13e9a15aee8af97f103484f8240a9cb3',
  },
  cimplPartitionSecrets: {
    label: 'CIMPL Partition PostgreSQL binding (fe56aa1b)',
    repo: 'cimpl-stack',
    path: 'src/cimpl/secrets.py',
    href: 'https://community.opengroup.org/osdu/platform/deployment-and-operations/cimpl-stack/-/blob/fe56aa1b13e9a15aee8af97f103484f8240a9cb3/src/cimpl/secrets.py',
    revision: 'fe56aa1b13e9a15aee8af97f103484f8240a9cb3',
  },
  partitionCacheFix: {
    label: 'Cache-read fallback fix (fc2dfbf)',
    repo: 'osdu-spi-partition',
    path: 'provider/partition-azure/src/main/java/org/opengroup/osdu/partition/provider/azure/service/PartitionServiceImpl.java',
    href: 'https://github.com/Azure/osdu-spi-partition/commit/fc2dfbf6f1a3038a804441aba615bf5ebadb3332',
  },
  ownership: {
    label: 'Why Azure source belongs to the fork',
    repo: 'osdu-spi',
    path: 'doc/src/adr/038-upstream-filter-transform.md',
    href: 'https://azure.github.io/osdu-spi/adr/038-upstream-filter-transform/',
  },
  concepts: {
    label: 'OSDU provider concepts',
    repo: 'osdu-spi',
    path: 'doc/src/concepts.md',
    href: 'https://azure.github.io/osdu-spi/concepts/',
  },
  engineering: {
    label: 'Engineering-system architecture',
    repo: 'osdu-spi',
    path: 'doc/src/architecture/overview.md',
    href: 'https://azure.github.io/osdu-spi/architecture/overview/',
  },
  branches: {
    label: 'Three-branch strategy',
    repo: 'osdu-spi',
    path: 'doc/src/architecture/three_branch_strategy.md',
    href: 'https://azure.github.io/osdu-spi/architecture/three_branch_strategy/',
  },
  proof: {
    label: 'Borrow, prove, restore',
    repo: 'osdu-spi',
    path: 'doc/src/adr/041-borrow-prove-restore-lane.md',
    href: 'https://azure.github.io/osdu-spi/adr/041-borrow-prove-restore-lane/',
  },
  forkTiers: {
    label: 'Service forks and customer mirrors',
    repo: 'osdu-spi',
    path: 'doc/src/architecture/fork_tiers.md',
    href: 'https://azure.github.io/osdu-spi/architecture/fork_tiers/',
  },
  gateway: {
    label: 'Gateway and ingress modes',
    repo: 'osdu-spi-stack',
    path: 'docs/design/gateway-ingress.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/gateway-ingress.md',
  },
  secrets: {
    label: 'Secret lifecycle and the credential seed',
    repo: 'osdu-spi-stack',
    path: 'docs/design/secret-lifecycle.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/secret-lifecycle.md',
  },
  smoke: {
    label: 'Scheduled smoke test and sweeper',
    repo: 'osdu-spi-stack',
    path: 'docs/design/ci-smoke.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/ci-smoke.md',
  },
  envLifecycle: {
    label: 'Shared environment lifecycle',
    repo: 'osdu-spi-stack',
    path: 'docs/design/environment-lifecycle.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/environment-lifecycle.md',
  },
  helmChart: {
    label: 'ADR-004 · One local Helm chart for Safeguards',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/004-local-helm-chart-safeguards.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/004-local-helm-chart-safeguards.md',
  },
  entra: {
    label: 'ADR-023 · Entra-only data plane',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/023-entra-only-data-plane.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/023-entra-only-data-plane.md',
  },
  imageLock: {
    label: 'ADR-017 · The osdu-image-lock ConfigMap',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/017-osdu-image-lock.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/017-osdu-image-lock.md',
  },
  schemaLoad: {
    label: 'ADR-013 · Schema load as a Flux-managed Job',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/013-schema-load-flux-job.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/013-schema-load-flux-job.md',
  },
  profiles: {
    label: 'ADR-021 · The minimal profile',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/021-middleware-only-minimal-profile.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/021-middleware-only-minimal-profile.md',
  },
  decisions: {
    label: 'The decision register (all ADRs)',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/README.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/README.md',
  },
  designs: {
    label: 'Design guides index',
    repo: 'osdu-spi-stack',
    path: 'docs/design/README.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/design/README.md',
  },
  namespaces: {
    label: 'ADR-006 · Three-namespace model',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/006-three-namespace-model.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/006-three-namespace-model.md',
  },
  ordering: {
    label: 'ADR-007 · Layered Kustomization ordering',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/007-layered-kustomization-ordering.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/007-layered-kustomization-ordering.md',
  },
  suspend: {
    label: 'ADR-014 · Suspend GitOps after deploy',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/014-suspend-gitops-after-deploy.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/014-suspend-gitops-after-deploy.md',
  },
  fluxNamespace: {
    label: 'ADR-019 · The osdu-flux namespace',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/019-osdu-flux-gitops-namespace.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/019-osdu-flux-gitops-namespace.md',
  },
  inventory: {
    label: 'ADR-025 · Single Flux inventory owner',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/025-single-flux-inventory-owner.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/025-single-flux-inventory-owner.md',
  },
  workloadIdentity: {
    label: 'ADR-005 · Workload Identity',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/005-workload-identity.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/005-workload-identity.md',
  },
  jwt: {
    label: 'ADR-016 · Istio JWT projection',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/016-istio-jwt-projection.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/016-istio-jwt-projection.md',
  },
  keyVault: {
    label: 'ADR-010 · Key Vault secret management',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/010-keyvault-secret-management.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/010-keyvault-secret-management.md',
  },
  resetBoundary: {
    label: 'ADR-029 · Lifecycle and reset boundary',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/029-environment-lifecycle-and-reset-boundary.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/029-environment-lifecycle-and-reset-boundary.md',
  },
  deployIdentity: {
    label: 'ADR-034 · Deploy identity survives down',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/034-deploy-identity-survives-down.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/034-deploy-identity-survives-down.md',
  },
  ephemeralPins: {
    label: 'ADR-031 · Fork images as ephemeral pins',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/031-fork-image-deploys-as-ephemeral-pins.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/031-fork-image-deploys-as-ephemeral-pins.md',
  },
  pinnedEnv: {
    label: 'ADR-028 · Version-pinned shared environment',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/028-version-pinned-shared-environment.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/028-version-pinned-shared-environment.md',
  },
  synchronization: {
    label: 'Upstream synchronization',
    repo: 'osdu-spi',
    path: 'doc/src/workflows/synchronization.md',
    href: 'https://azure.github.io/osdu-spi/workflows/synchronization/',
  },
  cascade: {
    label: 'Cascade integration',
    repo: 'osdu-spi',
    path: 'doc/src/workflows/cascade.md',
    href: 'https://azure.github.io/osdu-spi/workflows/cascade/',
  },
  validation: {
    label: 'Validation workflow',
    repo: 'osdu-spi',
    path: 'doc/src/workflows/validation.md',
    href: 'https://azure.github.io/osdu-spi/workflows/validation/',
  },
  release: {
    label: 'Release management',
    repo: 'osdu-spi',
    path: 'doc/src/workflows/release.md',
    href: 'https://azure.github.io/osdu-spi/workflows/release/',
  },
  adoption: {
    label: 'Adopting a mirror fork',
    repo: 'osdu-spi',
    path: 'doc/src/workflows/adoption.md',
    href: 'https://azure.github.io/osdu-spi/workflows/adoption/',
  },
  workflowSystem: {
    label: 'Template and fork workflows',
    repo: 'osdu-spi',
    path: 'doc/src/architecture/workflow_system.md',
    href: 'https://azure.github.io/osdu-spi/architecture/workflow_system/',
  },
  deployTest: {
    label: 'Deploy and test design',
    repo: 'osdu-spi',
    path: 'doc/src/architecture/deploy_test.md',
    href: 'https://azure.github.io/osdu-spi/architecture/deploy_test/',
  },
  descriptor: {
    label: 'The service descriptor',
    repo: 'osdu-spi',
    path: 'doc/src/runbooks/service-descriptor.md',
    href: 'https://azure.github.io/osdu-spi/runbooks/service-descriptor/',
  },
  forkLifecycle: {
    label: 'Fork lifecycle runbook',
    repo: 'osdu-spi',
    path: 'doc/src/runbooks/fork-lifecycle.md',
    href: 'https://azure.github.io/osdu-spi/runbooks/fork-lifecycle/',
  },
  learnings: {
    label: 'What was learned',
    repo: 'osdu-spi',
    path: 'doc/src/adr/learnings.md',
    href: 'https://azure.github.io/osdu-spi/adr/learnings/',
  },
  threeBranchDecision: {
    label: 'Three-branch strategy (decision)',
    repo: 'osdu-spi',
    path: 'doc/src/adr/001-three-branch-strategy.md',
    href: 'https://azure.github.io/osdu-spi/adr/001-three-branch-strategy/',
  },
  templateSync: {
    label: 'Template update propagation',
    repo: 'osdu-spi',
    path: 'doc/src/adr/012-template-update-propagation-strategy.md',
    href: 'https://azure.github.io/osdu-spi/adr/012-template-update-propagation-strategy/',
  },
  cascadeMonitor: {
    label: 'Cascade monitor and label states',
    repo: 'osdu-spi',
    path: 'doc/src/adr/019-cascade-monitor-pattern.md',
    href: 'https://azure.github.io/osdu-spi/adr/019-cascade-monitor-pattern/',
  },
  humanRequired: {
    label: 'The human-required label',
    repo: 'osdu-spi',
    path: 'doc/src/adr/020-human-required-label-strategy.md',
    href: 'https://azure.github.io/osdu-spi/adr/020-human-required-label-strategy/',
  },
  metaCommit: {
    label: 'Meta commit for Release Please',
    repo: 'osdu-spi',
    path: 'doc/src/adr/023-meta-commit-strategy-for-release-please.md',
    href: 'https://azure.github.io/osdu-spi/adr/023-meta-commit-strategy-for-release-please/',
  },
  ghcr: {
    label: 'GHCR as the image registry',
    repo: 'osdu-spi',
    path: 'doc/src/adr/033-ghcr-as-service-image-registry.md',
    href: 'https://azure.github.io/osdu-spi/adr/033-ghcr-as-service-image-registry/',
  },
  mavenProfile: {
    label: 'Azure-only Maven profile',
    repo: 'osdu-spi',
    path: 'doc/src/adr/035-azure-only-maven-profile.md',
    href: 'https://azure.github.io/osdu-spi/adr/035-azure-only-maven-profile/',
  },
  trustBoundaries: {
    label: 'Workflow trust boundaries',
    repo: 'osdu-spi',
    path: 'doc/src/adr/036-workflow-trust-boundaries.md',
    href: 'https://azure.github.io/osdu-spi/adr/036-workflow-trust-boundaries/',
  },
  mirrorSync: {
    label: 'Customer-tier mirror sync',
    repo: 'osdu-spi',
    path: 'doc/src/adr/039-customer-tier-mirror-sync.md',
    href: 'https://azure.github.io/osdu-spi/adr/039-customer-tier-mirror-sync/',
  },
  descriptorContract: {
    label: 'Descriptor-owned acceptance contract',
    repo: 'osdu-spi',
    path: 'doc/src/adr/040-descriptor-acceptance-contract.md',
    href: 'https://azure.github.io/osdu-spi/adr/040-descriptor-acceptance-contract/',
  },
  statusContract: {
    label: 'Machine-readable status contract',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/030-machine-readable-status-contract.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/030-machine-readable-status-contract.md',
  },
  forkRbac: {
    label: 'Environment deploy identity and namespace RBAC',
    repo: 'osdu-spi-stack',
    path: 'docs/decisions/032-environment-deploy-identity.md',
    href: 'https://github.com/Azure/osdu-spi-stack/blob/main/docs/decisions/032-environment-deploy-identity.md',
  },
};
